---
- name: Downloading gotop .tgz file
  ansible.builtin.get_url:
    url: "{{ gotop_repository }}{{ gotop_filename }}"
    dest: /tmp
    mode: 0644

- name: Extract gotop .tgz package at /usr/local/bin
  ansible.builtin.unarchive:
    src: "/tmp/{{ gotop_filename }}"
    dest: /usr/local/bin
    mode: 0755
    remote_src: yes

- name: Delete gotop .tgz package at /tmp
  ansible.builtin.file:
    path: "/tmp/{{ gotop_filename }}"
    state: absent
